# Rustfmt configuration
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Import formatting
reorder_imports = true
reorder_modules = true
group_imports = "StdExternalCrate"

# Function formatting
fn_args_layout = "Tall"
where_single_line = false

# Control flow formatting
control_brace_style = "AlwaysSameLine"
else_if_brace_style = "AlwaysSameLine"

# Miscellaneous
remove_nested_parens = true
use_field_init_shorthand = true
force_explicit_abi = true
normalize_comments = true
normalize_doc_attributes = true