name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libtss2-dev tpm2-tools

    - name: Build and test Rust
      run: |
        cargo build --lib
        cargo test --lib

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build Rust library (release)
      run: cargo build --lib --release

    - name: Build Java JAR
      working-directory: java
      run: mvn clean package

    - name: Run Java tests
      working-directory: java
      run: mvn test
      continue-on-error: true
